language: clojure
jdk:
- oraclejdk8
lein: 2.7.1
cache:
  directories:
  - "$HOME/.lein"
  - "$HOME/.m2"
  - "$HOME/.nvm"
  - "node_modules/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install karma karma-cljs-test karma-firefox-launcher
  - npm install -g karma-cli
script:
  - lein cljfmt check
  - lein test
  - lein doo firefox test
  - lein uberjar
after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
env:
  global:
  - CODECOV_TOKEN=275b997d-0ce5-4a97-a379-3610b958dd1a
notifications:
  email: false
addons:
  firefox: "39.0"
